import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import dbConnect from '@/lib/db';
import { Application } from '@/models';
import { createInvoice, processPdfData } from '@/lib/billing';
import { sendEmail } from '@/lib/mailer';

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session) {
      return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { applicationId } = body;

    if (!applicationId) {
      return NextResponse.json({ message: 'Application ID required' }, { status: 400 });
    }

    await dbConnect();

    const application = await Application.findById(applicationId);
    if (!application) {
      return NextResponse.json({ message: 'Application not found' }, { status: 404 });
    }

    if (application.invoiceSent && application.invoiceNumber) {
        return NextResponse.json({ message: 'Invoice already generated' }, { status: 400 });
    }

    // Generate Invoice
    try {
        const { getStripePrice } = await import('@/lib/stripe');
        const price = getStripePrice();

        const invoiceResult = await createInvoice({
            name: application.billingName || application.clubName,
            zip: application.billingZip || '0000',
            city: application.billingCity || 'Unknown',
            address: application.billingAddress || 'Unknown',
            taxNumber: application.billingTaxNumber,
            email: application.billingEmail || application.applicantEmail,
            paymentMethod: application.paymentMethod || 'transfer',
            amount: price,
            isPaid: true,
            comment: `Generated by Admin: ${session.user?.email}`
        });

        if (invoiceResult && !invoiceResult.skipped) {
            application.invoiceSent = true;
            application.invoiceNumber = invoiceResult.invoiceId;
            application.paymentStatus = 'paid';
            
            await application.save();

            // Send Email with Attachment
            if (invoiceResult.pdf) {
                const pdfBuffer = await processPdfData(invoiceResult.pdf, invoiceResult.invoiceId);
                if (pdfBuffer) {
                    const targetEmail = application.billingEmail || application.applicantEmail;
                    if (targetEmail) {
                        await sendEmail({
                            to: targetEmail,
                            subject: `Számla - ${application.clubName} - OAC Liga`,
                            html: `
                            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
                                <div style="background-color: #059669; padding: 20px; text-align: center;">
                                    <h1 style="color: white; margin: 0; font-size: 24px;">Elektronikus Számla</h1>
                                </div>
                                <div style="padding: 24px; background-color: #ffffff; color: #374151; line-height: 1.6;">
                                    <p>Kedves <strong>${application.billingName || application.clubName}</strong>!</p>
                                    <p>Köszönjük a befizetést! Mellékelten küldjük a(z) <strong>${invoiceResult.invoiceId}</strong> számú elektronikus számlát az OAC liga csatlakozási díjáról.</p>
                                    <p>Sikeres versenyzést kívánunk!</p>
                                    <div style="margin-top: 30px; padding-top: 20px; border-t: 1px solid #e5e7eb; font-size: 0.9em; color: #6b7280;">
                                        Üdvözlettel,<br>
                                        OAC Csapat & MDSZ
                                    </div>
                                </div>
                            </div>
                            `,
                            attachments: [
                                {
                                    filename: `szamla_${invoiceResult.invoiceId}.pdf`,
                                    content: pdfBuffer,
                                    contentType: 'application/pdf'
                                }
                            ]
                        });
                    }
                }
            }

            return NextResponse.json({ 
                message: 'Invoice generated and email sent', 
                invoiceNumber: invoiceResult.invoiceId 
            });
        } else {
            return NextResponse.json({ message: 'Invoice generation skipped by provider settings' }, { status: 500 });
        }
    } catch (billingError: any) {
        console.error('Manual billing error:', billingError);
        return NextResponse.json({ message: 'Billing failed: ' + billingError.message }, { status: 500 });
    }

  } catch (error: any) {
    console.error('Generate invoice error:', error);
    return NextResponse.json({ message: 'Internal Server Error' }, { status: 500 });
  }
}
