"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from "recharts";

interface GrowthDataItem {
  name: string;
  value: number;
}

interface VerifiedGrowthChartProps {
  clubData?: GrowthDataItem[];
  tournamentData?: GrowthDataItem[];
}

export function VerifiedGrowthChart({ clubData = [], tournamentData = [] }: VerifiedGrowthChartProps) {
  // Merge data for combined chart if needed, or just display side by side trends. 
  // For simplicity since they share the same x-axis (months), we can merge them by index if they align, 
  // or just Map names found in both.
  
  // Assumption: both arrays have same length and same 'name' (months) generated by backend
  const chartData = clubData.map((item, index) => ({
      name: item.name,
      clubs: item.value,
      tournaments: tournamentData[index]?.value || 0
  }));

  return (
    <Card className="col-span-1 md:col-span-2 lg:col-span-2 h-full min-h-[400px] bg-card/40 backdrop-blur-sm border-border/50">
      <CardHeader>
        <CardTitle className="text-xl font-bold">Növekedési Statisztikák</CardTitle>
        <CardDescription>Ellenőrzött Klubok és Versenyek száma az elmúlt 6 hónapban</CardDescription>
      </CardHeader>
      <CardContent className="pl-0 pb-0">
        <div className="h-[320px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={chartData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorClubs" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.3}/>
                  <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                </linearGradient>
                <linearGradient id="colorTournaments" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#22c55e" stopOpacity={0.3}/>
                  <stop offset="95%" stopColor="#22c55e" stopOpacity={0}/>
                </linearGradient>
              </defs>
              <XAxis dataKey="name" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
              <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
              <Tooltip 
                contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '8px', color: 'hsl(var(--foreground))' }}
              />
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))" opacity={0.4} />
              <Legend verticalAlign="top" height={36}/>
              <Area 
                type="monotone" 
                dataKey="clubs" 
                name="Klubok"
                stroke="#8b5cf6" 
                fillOpacity={1} 
                fill="url(#colorClubs)" 
                strokeWidth={2} 
              />
              <Area 
                type="monotone" 
                dataKey="tournaments" 
                name="Versenyek"
                stroke="#22c55e" 
                fillOpacity={1} 
                fill="url(#colorTournaments)" 
                strokeWidth={2} 
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}
